### ISSUE TITLE
Self-Hosted Runner Abuse Tooling

### ISSUE THREAD

**Issue by AdnaneKhan** [nikitastupin/pwnhub#1]
Love this repository; fantastic work with the attack workflow diagrams you recently added!

My colleagues and I wrote open-source tooling to abuse self-hosted runners. It would be great to reference the tool from here!

https://github.com/praetorian-inc/gato
https://www.praetorian.com/blog/self-hosted-github-runners-are-backdoors/

It also opens up some exciting attack paths when looking at the interaction between the runner, GITHUB_TOKEN, and other secrets.

Happy to answer any questions :)

**Comment by nikitastupin** [comment]
Hey @AdnaneKhan,

Thank you for sharing, the tool looks very promising!

As far as I see the tool is designed to prove impact of a compromised PAT and somehow can prove impact of a self-hosted runner. Could you elaborate how it does the latter?

**Comment by AdnaneKhan** [comment]
> Hey @AdnaneKhan,
> 
> 
> 
> Thank you for sharing, the tool looks very promising!
> 
> 
> 
> As far as I see the tool is designed to prove impact of a compromised PAT and somehow can prove impact of a self-hosted runner. Could you elaborate how it does the latter?

The tool has a few features as part of the attack and enumerate modules that can be used to identify and abuse a self-hosted runner.

The first attack feature is automatically pushing a new workflow to a feature branch that runs on a self-hosted runner (requires write access with repo and workflow scopes token). This workflow can contain arbitrary shell commands. This isn't any different than doing it manually via Git, but it's quite a lot faster.

The second feature is creation of a fork PR containing a new workflow that runs on a self-hosted runner (this can be done on public repositories). By default GitHub requires approval for first time contributors to run workflows on the pull_request trigger, but even a simple documentation change would make you a contributor to a repository.

Finally, as part of the enumeration module Gato will download run logs for workflows via the GitHub API and parse out the machine name of the runner. This can be used to find repositories that are using non-ephemeral runners (the runner name will often hint whether the runner is ephemeral or not).

**Comment by nikitastupin** [comment]
Thank you for the details! This makes sense and I've started a separate file with tools https://github.com/nikitastupin/pwnhub/commit/0f9f96c9316441679d104f7c6043caf16abfee2a where I've added Gato
